#!/bin/bash

export joy_path=/opt/joy_framework

# Code Defination
cscope-php $joy_path

cd $joy_path

# Code Index
exec ctags-exuberant -f ~/.vim/mytags/joy_framework \
-h ".php" -R \
--exclude="\.svn" \
--totals=yes \
--tag-relative=yes \
--PHP-kinds=+cf \
--regex-PHP='/abstract class ([^ ]*)/\1/c/' \
--regex-PHP='/interface ([^ ]*)/\1/c/' \
--regex-PHP='/(public |static |abstract |protected |private )+function ([^ (]*)/\2/f/'
